"use client";

import Link from "next/link";
import { ArrowUpRight, Check, Clock3, MoreHorizontal, Plus, Ticket, UsersRound } from "lucide-react";
import { employee, employeeActivity, employeeNotifications, employeeTasks, type EmployeeTask } from "@/lib/employee-data";

const toneClasses = {
  blue: "bg-primary/10 text-primary",
  green: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
  amber: "bg-amber-500/10 text-amber-600 dark:text-amber-400",
  slate: "bg-muted text-muted-foreground",
};

function MetricCard({ label, value, detail, icon: Icon, tone = "default" }: { label: string; value: string; detail: string; icon: typeof Clock3; tone?: "default" | "warning" | "success" }) {
  const toneClass = tone === "warning" ? "bg-amber-500/10 text-amber-600 dark:text-amber-400" : tone === "success" ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" : "bg-primary/10 text-primary";
  return <div className="rounded-xl border border-border/70 bg-card p-4 shadow-xs"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p></div><div className={`grid size-9 place-items-center rounded-lg ${toneClass}`}><Icon className="size-4" /></div></div><p className="mt-2 text-xs text-muted-foreground">{detail}</p></div>;
}

function TaskStatus({ status }: { status: EmployeeTask["status"] }) {
  const classes = status === "Completed" ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" : status === "In progress" ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground";
  return <span className={`rounded-full px-2 py-1 text-[10px] font-medium ${classes}`}>{status}</span>;
}

export default function EmployeeDashboard() {
  return <div className="space-y-6">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-muted-foreground">Tuesday, 11 August 2026</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">Good morning, {employee.name.split(" ")[0]}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Here is what needs your attention across your assigned clients today.</p></div><div className="flex items-center gap-2"><Link href="/dashboard/myTasks" className="inline-flex h-9 items-center gap-2 rounded-lg border border-border bg-card px-3 text-sm font-medium shadow-xs hover:bg-muted"><Plus className="size-4" /> Add task</Link><Link href="/dashboard/myActivity" className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground shadow-xs hover:bg-primary/90">View activity <ArrowUpRight className="size-4" /></Link></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="My tasks" value="14" detail="5 due today" icon={Check} /><MetricCard label="In progress" value="5" detail="2 marked high priority" icon={Clock3} tone="warning" /><MetricCard label="Completed this week" value="9" detail="Up 12% from last week" icon={Check} tone="success" /><MetricCard label="Assigned clients" value={String(employee.assignedClients)} detail="3 with active shipments" icon={UsersRound} /></section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,0.65fr)]"><div className="rounded-xl border border-border/70 bg-card shadow-xs"><div className="flex items-center justify-between border-b border-border/60 px-4 py-3 sm:px-5"><div><h2 className="text-sm font-semibold">Today&apos;s priorities</h2><p className="mt-0.5 text-xs text-muted-foreground">Your most important work at a glance</p></div><Link href="/dashboard/myTasks" className="text-xs font-medium text-primary hover:underline">View all</Link></div><div className="divide-y divide-border/60">{employeeTasks.slice(0, 3).map((task) => <div key={task.id} className="flex items-center gap-3 px-4 py-4 sm:px-5"><div className={`grid size-8 shrink-0 place-items-center rounded-lg ${task.priority === "High" ? "bg-amber-500/10 text-amber-600 dark:text-amber-400" : "bg-muted text-muted-foreground"}`}><Check className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-medium">{task.title}</p><TaskStatus status={task.status} /></div><p className="mt-1 truncate text-xs text-muted-foreground">{task.context} · {task.due}</p></div><button aria-label={`More options for ${task.title}`} className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted"><MoreHorizontal className="size-4" /></button></div>)}</div><div className="border-t border-border/60 px-4 py-3 sm:px-5"><Link href="/dashboard/myTasks" className="text-xs font-medium text-muted-foreground hover:text-foreground">Open task workspace →</Link></div></div>
      <div className="rounded-xl border border-border/70 bg-card shadow-xs"><div className="flex items-center justify-between border-b border-border/60 px-4 py-3 sm:px-5"><div><h2 className="text-sm font-semibold">Attention needed</h2><p className="mt-0.5 text-xs text-muted-foreground">Items that may need a response</p></div><Ticket className="size-4 text-muted-foreground" /></div><div className="space-y-3 p-4 sm:p-5">{employeeNotifications.map((notification) => <div key={notification.id} className="rounded-lg border border-border/60 bg-muted/25 p-3"><div className="flex items-start gap-2.5"><span className={`mt-0.5 size-2 shrink-0 rounded-full ${notification.tone === "warning" ? "bg-amber-500" : notification.tone === "success" ? "bg-emerald-500" : "bg-primary"}`} /><div><p className="text-xs font-medium">{notification.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{notification.detail}</p></div></div></div>)}<Link href="/dashboard/notifications" className="block pt-1 text-xs font-medium text-primary hover:underline">View notifications →</Link></div></div></section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(280px,0.6fr)]"><div className="rounded-xl border border-border/70 bg-card shadow-xs"><div className="flex items-center justify-between border-b border-border/60 px-4 py-3 sm:px-5"><div><h2 className="text-sm font-semibold">Recent activity</h2><p className="mt-0.5 text-xs text-muted-foreground">Your latest workspace actions</p></div><Link href="/dashboard/myActivity" className="text-xs font-medium text-primary hover:underline">See history</Link></div><div className="divide-y divide-border/60">{employeeActivity.map((activity) => <div key={activity.id} className="flex items-center gap-3 px-4 py-3.5 sm:px-5"><span className={`grid size-8 shrink-0 place-items-center rounded-full text-[10px] ${toneClasses[activity.tone]}`}><Check className="size-3.5" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{activity.title}</p><p className="truncate text-xs text-muted-foreground">{activity.detail}</p></div><span className="shrink-0 text-[11px] text-muted-foreground">{activity.time}</span></div>)}</div></div><div className="rounded-xl border border-primary/20 bg-primary/[0.04] p-5"><p className="text-xs font-semibold uppercase tracking-widest text-primary">Workspace snapshot</p><h2 className="mt-3 text-lg font-semibold tracking-tight">Your client desk is ready.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">You currently own the day-to-day relationship for {employee.assignedClients} clients. New client tickets will appear here first.</p><Link href="/dashboard/support" className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-primary hover:underline">Open support desk <ArrowUpRight className="size-3.5" /></Link></div></section>
  </div>;
}
