"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowUpRight, MapPin, Package, Search, UsersRound } from "lucide-react";
import { useEmployee } from "@/components/dashboard/employee-provider";

export default function MyClients() {
  const { getVisibleClients, can } = useEmployee();
  const [query, setQuery] = useState("");
  const clients = useMemo(() => getVisibleClients().filter((client) => `${client.name} ${client.contact} ${client.location} ${client.status}`.toLowerCase().includes(query.toLowerCase())), [getVisibleClients, query]);
  if (!can("clients.view")) return <div className="grid min-h-[420px] place-items-center rounded-xl border border-dashed border-border text-center"><div><p className="text-xs font-semibold uppercase tracking-wider text-destructive">Permission required</p><h1 className="mt-2 text-xl font-semibold">Clients are not available</h1><p className="mt-2 text-sm text-muted-foreground">Master has not supplied client visibility to this employee.</p></div></div>;
  return <div className="space-y-6"><div><div className="flex items-center gap-2 text-xs font-medium text-primary"><UsersRound className="size-4" /> My work</div><h1 className="mt-2 text-2xl font-semibold tracking-tight">My clients</h1><p className="mt-2 text-sm text-muted-foreground">Open a client workspace to resolve shipment issues on their behalf.</p></div><label className="relative block max-w-lg"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search assigned clients..." className="h-10 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm outline-none focus:border-primary" /></label>{clients.length ? <div className="grid gap-4 lg:grid-cols-2">{clients.map((client) => <div key={client.id} className="rounded-xl border border-border/70 bg-card p-5 shadow-xs"><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-semibold">{client.name}</h2><p className="mt-1 text-xs text-muted-foreground">Primary contact: {client.contact}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${client.status === "Needs attention" ? "bg-amber-500/10 text-amber-600 dark:text-amber-400" : "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"}`}>{client.status}</span></div><div className="mt-5 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><MapPin className="size-3.5" />{client.location}</span><span className="inline-flex items-center gap-1.5"><Package className="size-3.5" />{client.shipments} active shipments</span></div><p className="mt-4 text-xs text-muted-foreground">{client.lastActivity}</p><Link prefetch={false} href={`/dashboard/myClients/${client.id}`} className="mt-5 inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-sm font-medium text-primary-foreground hover:bg-primary/90">Open client workspace <ArrowUpRight className="size-4" /></Link></div>)}</div> : <div className="rounded-xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No assigned clients match this search.</div>}</div>;
}
