"use client";

import { useState } from "react";
import { ArrowRight, Check, ClipboardList, FileBarChart, PackagePlus, Search, Truck, X } from "lucide-react";
import { useEmployee } from "@/components/dashboard/employee-provider";
import type { PermissionKey } from "@/lib/employee-data";

type Mode = "booking" | "tracking" | "pickup" | "reports";
const config: Record<Mode, { title: string; eyebrow: string; description: string; permission: PermissionKey; icon: typeof Truck }> = {
  booking: { title: "Booking desk", eyebrow: "Operations", description: "Create a frontend shipment booking on behalf of an assigned client.", permission: "booking.view", icon: PackagePlus },
  tracking: { title: "Tracking desk", eyebrow: "Operations", description: "Review milestones and record the next operational tracking action.", permission: "tracking.view", icon: Truck },
  pickup: { title: "Pickup desk", eyebrow: "Operations", description: "Schedule and monitor pickup commitments for assigned clients.", permission: "pickup.view", icon: ClipboardList },
  reports: { title: "Reports desk", eyebrow: "Insights", description: "Review local operational summaries available to this employee.", permission: "reports.view", icon: FileBarChart },
};

export default function OperationsWorkspace({ mode }: { mode: Mode }) {
  const { profile, can, getVisibleClients, shipments, addActivity } = useEmployee();
  const copy = config[mode];
  const Icon = copy.icon;
  const [query, setQuery] = useState("");
  const [selectedClient, setSelectedClient] = useState(getVisibleClients()[0]?.id ?? "");
  const [notice, setNotice] = useState("");
  const clients = getVisibleClients();
  const visibleShipments = shipments.filter((shipment) => profile.assignedClientIds.includes(shipment.clientId) && `${shipment.id} ${shipment.route} ${shipment.status}`.toLowerCase().includes(query.toLowerCase()));
  if (!can(copy.permission)) return <Unauthorized title={copy.title} />;
  const action = (message: string) => { addActivity(message, `${clients.find((client) => client.id === selectedClient)?.name ?? "Assigned client"} · frontend demo`, "green"); setNotice(`${message} recorded locally.`); };
  return <div className="space-y-6"><header><div className="flex items-center gap-2 text-xs font-medium text-primary"><Icon className="size-4" /> {copy.eyebrow}</div><h1 className="mt-2 text-2xl font-semibold tracking-tight">{copy.title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{copy.description}</p></header>{notice && <div role="status" className="flex items-center gap-2 rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-xs text-emerald-700 dark:text-emerald-300"><Check className="size-4" />{notice}<button className="ml-auto" aria-label="Dismiss notice" onClick={() => setNotice("")}><X className="size-3.5" /></button></div>}<div className="flex flex-col gap-3 rounded-xl border border-border/70 bg-card p-3 shadow-xs sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search assigned records..." className="h-10 w-full rounded-lg border border-input bg-background pl-9 pr-3 text-sm outline-none focus:border-primary" /></label><select value={selectedClient} onChange={(event) => setSelectedClient(event.target.value)} className="h-10 rounded-lg border border-input bg-background px-3 text-sm"><option value="">All assigned clients</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></div>{mode === "reports" ? <ReportCards onAction={action} /> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visibleShipments.filter((shipment) => !selectedClient || shipment.clientId === selectedClient).map((shipment) => <article key={shipment.id} className="rounded-xl border border-border/70 bg-card p-4 shadow-xs"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{shipment.id}</p><p className="mt-1 text-xs text-muted-foreground">{shipment.route}</p></div><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-semibold">{shipment.status}</span></div><p className="mt-4 text-xs text-muted-foreground">ETA: <strong className="text-foreground">{shipment.eta}</strong></p><button onClick={() => action(mode === "booking" ? "Shipment booking" : mode === "tracking" ? "Tracking update" : "Pickup request")} className="mt-4 inline-flex h-9 w-full items-center justify-center gap-2 rounded-lg bg-primary text-xs font-semibold text-primary-foreground">{mode === "booking" ? "Book shipment" : mode === "tracking" ? "Record update" : "Schedule pickup"}<ArrowRight className="size-3.5" /></button></article>)}{!visibleShipments.length && <EmptyState />}</div>}</div>;
}

function ReportCards({ onAction }: { onAction: (message: string) => void }) { return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{["Assigned client health", "Shipment performance", "Pickup commitments", "Support SLA", "Activity summary", "Weekly workload"].map((title, index) => <article key={title} className="rounded-xl border border-border/70 bg-card p-4 shadow-xs"><p className="text-sm font-semibold">{title}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{["94%", "82", "12", "91%", "28", "14"][index]}</p><p className="mt-1 text-xs text-muted-foreground">Frontend demo summary · updated today</p><button onClick={() => onAction(`Exported ${title}`)} className="mt-4 inline-flex items-center gap-1.5 text-xs font-semibold text-primary">Export summary <ArrowRight className="size-3.5" /></button></article>)}</div>; }
function EmptyState() { return <div className="rounded-xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground md:col-span-2 xl:col-span-3">No assigned records match this search.</div>; }
function Unauthorized({ title }: { title: string }) { return <div className="grid min-h-[420px] place-items-center rounded-xl border border-dashed border-border p-8 text-center"><div><p className="text-xs font-semibold uppercase tracking-wider text-destructive">Permission required</p><h1 className="mt-2 text-xl font-semibold">{title} is not available</h1><p className="mt-2 max-w-md text-sm text-muted-foreground">This employee does not have the permission supplied by Master for this workspace.</p></div></div>; }
