import { NextResponse } from "next/server";
import { requireEmployeeAccess } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
const allowed = new Set(["application/pdf", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]); const MAX_BYTES = 10 * 1024 * 1024;

async function access(clientId?: string) {
  const actor = await requireEmployeeAccess(); const supabase = await createClient();
  const { data: permission } = await supabase.rpc("has_permission", { required_permission: "rate_cards.manage" });
  if (!permission) return { error: NextResponse.json({ error: "You do not have rate-card access." }, { status: 403 }) };
  if (clientId) { const { data: assigned } = await supabase.from("employee_client_assignments").select("client_id").eq("employee_user_id", actor.userId).eq("client_id", clientId).maybeSingle(); if (!assigned) return { error: NextResponse.json({ error: "This client is outside your assigned scope." }, { status: 403 }) }; }
  return { actor };
}
export async function GET() { const result = await access(); if (result.error) return result.error; const supabase = await createClient(); const { data, error } = await supabase.from("rate_cards").select("id,client_id,original_filename,mime_type,byte_size,updated_at,client_accounts(legal_name,client_code)").order("updated_at", { ascending: false }); if (error) return NextResponse.json({ error: "Unable to load rate cards." }, { status: 500 }); return NextResponse.json({ rateCards: data ?? [] }); }
export async function POST(request: Request) { const form = await request.formData(); const clientId = String(form.get("clientId") ?? ""); const file = form.get("file"); const result = await access(clientId); if (result.error) return result.error; if (!(file instanceof File) || !allowed.has(file.type) || file.size < 1 || file.size > MAX_BYTES) return NextResponse.json({ error: "Upload a PDF or XLSX file up to 10 MB." }, { status: 400 }); const admin = createAdminClient(); const { data: previous } = await admin.from("rate_cards").select("object_path").eq("client_id", clientId).maybeSingle(); const path = `${clientId}/${crypto.randomUUID()}.${file.type === "application/pdf" ? "pdf" : "xlsx"}`; const upload = await admin.storage.from("rate-cards").upload(path, file, { contentType: file.type }); if (upload.error) return NextResponse.json({ error: "Unable to upload rate card." }, { status: 500 }); const { error } = await admin.from("rate_cards").upsert({ client_id: clientId, object_path: path, original_filename: file.name, mime_type: file.type, byte_size: file.size, uploaded_by: result.actor!.userId, updated_at: new Date().toISOString() }, { onConflict: "client_id" }); if (error) { await admin.storage.from("rate-cards").remove([path]); return NextResponse.json({ error: "Unable to save rate-card metadata." }, { status: 500 }); } if (previous?.object_path) await admin.storage.from("rate-cards").remove([previous.object_path]); return NextResponse.json({ ok: true }); }
export async function PATCH(request: Request) { const { clientId } = await request.json() as { clientId?: string }; const result = await access(clientId); if (result.error) return result.error; const admin = createAdminClient(); const { data } = await admin.from("rate_cards").select("object_path").eq("client_id", clientId).maybeSingle(); if (!data) return NextResponse.json({ error: "Rate card was not found." }, { status: 404 }); const signed = await admin.storage.from("rate-cards").createSignedUrl(data.object_path, 60); return signed.error ? NextResponse.json({ error: "Unable to prepare download." }, { status: 500 }) : NextResponse.json({ url: signed.data.signedUrl }); }
